#!/usr/bin/env bash
# Install nginx web server and set its root / to return a hello world

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
