#!/usr/bin/env bash
# /redirect_me has to redirect the server to another page

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo chmod 777 /etc/nginx/sites-enabled/default
sed -i "/listen 80 default_server;/a return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" /etc/nginx/sites-enabled/default
sudo service nginx restart
