#!/usr/bin/env bash
# 404 not found custom page

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server;/a return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo sed -i '/^\tserver_name.*/a error_page 404 \/error404.html;' /etc/nginx/sites-enabled/default
sudo service nginx restart
